---
# Zookeeper Version Download

zookeeper_version: "3.4.10"
zookeeper_build_name: "zookeeper-{{ zookeeper_version }}"
zookeeper_package: "{{ zookeeper_build_name }}.tar.gz"
zookeeper_url: "http://apache.claz.org/zookeeper/stable/{{ zookeeper_package }}"

# Zookeeper installation directory

zookeeper_home_dir: "/opt/{{ zookeeper_build_name }}"
zookeeper_app_path: /etc/zookeeper
zookeeper_data_dir: "/var/lib/zookeeper"
zookeeper_log_data_dir: "/var/log/zookeeper"

# Zookeeper user and group

zookeeper_user: zookeeper
zookeeper_group: zookeeper

# Zookeeper user and group

zookeeper_max_client_connections: 50
zookeeper_tick_time: 2000
zookeeper_initial_limit: 100
zookeeper_sync_limit: 5
zookeeper_server_jvmflags: ""
zookeeper_client_port: 2181
numbers: [ 1, 2, 3 ]      #serial myid for each quorom servers
zookeeper_servers:        #use dns address instead of ip address. do  not use 127.0.0.1
  - { index: "1", dns: "ec2-54-210-126-89.compute-1.amazonaws.com", ports: "2881:3881" }
  - { index: "2", dns: "ec2-52-91-106-158.compute-1.amazonaws.com", ports: "2881:3881" }
  - { index: "3", dns: "ec2-52-23-162-232.compute-1.amazonaws.com", ports: "2881:3881" }
