---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [variable]

- name: Ensure zookeeper is installed.
  become: yes
  package:
    name: "{{ zookeeper_package_name }}"
    state: present
  notify:
    - Enable Zookeeper
  tags: [install]

- name: Configure Zookeeper ID
  template: src=myid.j2 dest={{ zookeeper_data_dir }}/myid
  register: zookeeper_id_file
  notify:
    - Restart Zookeeper
  tags: [config_id]

- name: Configure Zookeeper
  template: src=zoo.cfg.j2 dest={{ zookeeper_conf_dir }}/zoo.cfg
  notify:
    - Restart Zookeeper
  tags: [config_zk]
  
#- name: Configure Zookeeper JVM Properties
