---
# Zookeeper Version Download

zookeeper_version: "3.4.10"
zookeeper_build_name: "zookeeper-{{ zookeeper_version }}"
zookeeper_package: "{{ zookeeper_build_name }}.tar.gz"
zookeeper_url: "http://apache.claz.org/zookeeper/stable/{{ zookeeper_package }}"

# Zookeeper installation directory

zookeeper_home_dir: "/opt/{{ zookeeper_build_name }}"
zookeeper_conf_dir: " /opt/zookeeper/conf"
zookeeper_data_dir: "/var/lib/zookeeper"
zookeeper_log_data_dir: "/var/log/zookeeper"

# Zookeeper user and group

zookeeper_user: zookeeper
zookeeper_group: zookeeper

# Zookeeper user and group

zookeeper_max_client_connections: 50
zookeeper_tick_time: 2000
zookeeper_initial_limit: 100
zookeeper_sync_limit: 5
zookeeper_server_jvmflags: ""
number_of_participants: 3   #this should be changed if number of participants get change. change the following list accordingly
numbers: [ 0, 1, 2, 3 ]     # first 0 for only conf/zoo.cfg. there will be also conf1,conf2,conf3 ... directories
zookeeper_client_port: 218  #last digit will be provided via looping. actual port is 2181
zookeeper_servers:
  - { index: "1", ip: "127.0.0.1", ports: "2881:3881" }
  - { index: "2", ip: "127.0.0.1", ports: "2882:3882" }
  - { index: "3", ip: "127.0.0.1", ports: "2883:3883" }
